- name: Update APT packages
  apt:
    update_cache: yes
    upgrade: full
  become: true
  tags: apt

- name: Install software
  apt:
    name:
      - tmux
      - htop
      - rsync
      - i2c-tools
    state: present
  become: true
  tags: apt

- name: Copy the public key of the user who is running ansible to the remote machine
  authorized_key:
    user: pi
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  tags: ssh

- name: Start the ssh service
  systemd:
    name: ssh
    state: started
    enabled: true
  become: true

- name: No stupid login message
  file:
    path:  /home/pi/.hushlogin
    state: touch
    owner: pi
    group: pi
    mode:  "0755"

- name: Set keyboard layout to DE
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644
  become: true

- name: Create influxdb user with READ-only access
  shell: "influx
            -host '{{ influxdb_host }}'
            -ssl
            -port {{ influxdb_port }}
            -username {{ influxdb_admin_user }}
            -password {{ influxdb_admin_password }}
            -execute \"CREATE USER {{ influxdb_wordclock_user }} WITH PASSWORD '{{ influxdb_wordclock_password }}';
                       GRANT READ ON {{ sensor }} TO {{ influxdb_wordclock_user }}\""
  tags: telegraf,grafana
