- cron:
    env: yes
    name: PATH
    value: "/usr/local/bin:/usr/bin:/bin"
  tags: cron
- cron:
    env: yes
    name: BUNDLE_GEMFILE
    value: "{{ ansistrano_deploy_to }}/current/Gemfile"
  tags: cron
- cron:
    name: "Update time at wordclock"
    job: "bundle exec {{ ansistrano_deploy_to }}/current/exe/wordclock"
  tags: cron
