AllCops:
  TargetRubyVersion: 3.3
  Include:
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/*.gemspec'
    - '**/Rakefile'
    - 'exe/*'
  Exclude:
    - vendor/**/*
    - db/migrations/**/*

  DisplayCopNames:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

  NewCops: enable

Layout/LineLength:
  Max: 180
