- name: fcserver exists
  stat:
    path: /usr/sbin/fcserver
  register: fcserver_check
- name: git is installed
  ansible.builtin.package:
    name: git
    state: present
  when: not fcserver_check.stat.exists
- name: fadecandy repository is cloned
  ansible.builtin.git:
    repo: https://git.approximate.life/fadecandy.git
    dest: /tmp/fadecandy
    depth: 1
    update: no      # Prevents Ansible from checking for changes/new commits
    version: HEAD   # Explicitly set the branch/commit
    recursive: no   # IMPORTANT: Prevents recursive submodule loading
  when: not fcserver_check.stat.exists
- name: fcserver binary is at location
  ansible.builtin.copy:
    src: /tmp/fadecandy/bin/fcserver-rpi
    dest: /usr/sbin/fcserver
    owner: root
    mode: '0755'
    remote_src: yes
  become: true
  when: not fcserver_check.stat.exists
- name: Remove temporary fadecandy repository clone
  file:
    path: /tmp/fadecandy
    state: absent
- name: /etc/fadecandy exists
  ansible.builtin.file:
    path: /etc/fadecandy
    state: directory
  become: true
- name: config.json is in place
  ansible.builtin.copy:
    src: config.json
    dest: /etc/fadecandy/config.json
    mode: "0755"
  become: true
- name: fcserver systemd service is configured
  ansible.builtin.copy:
    src: fcserver.service
    dest: /etc/systemd/system/fcserver.service
    mode: "0664"
  become: true
- name: fadecandy service is started
  ansible.builtin.systemd:
    name: fcserver
    state: started
    enabled: true
  become: true
