# https://github.com/scanlime does not exist anymore :-/
# There is a backup at diskstation:/volume1/backup/fcserver-rpi
# - name: Download fcserver
#   get_url:
#     url: "https://github.com/scanlime/fadecandy/raw/master/bin/fcserver-rpi"
#     dest: "/usr/sbin/fcserver"
#     owner: "root"
#     mode: "0755"
#   become: true

- name: Create the /etc/fadecandy directory
  file:
    path: /etc/fadecandy
    state: directory
  become: true

- name: Put config.json in place
  copy:
    src: "config.json"
    dest: "/etc/fadecandy/config.json"
    mode: "0755"
  become: true

- name: Create fcserver systemd service config
  copy:
    src: "fcserver.service"
    dest: "/etc/systemd/system/fcserver.service"
    mode: "0664"
  become: true

- name: Start the fadecandy service
  systemd:
    name: fcserver
    state: started
    enabled: true
  become: true
