#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'word_clock/clock_24'
require 'word_clock/xkcd_colors'
require 'word_clock/color_picker'
require 'faderuby'

client = FadeRuby::Client.new(
  ENV.fetch('OPC_HOST', 'localhost'),
  ENV.fetch('OPC_PORT', '7890').to_i
)

strip = FadeRuby::Strip.new(18 * 16)
strip.set_all(r: 0, g: 0, b: 0)
client.write(strip)

clock = WordClock::Clock24.new

(0..23).each do |hour|
  (0..59).each do |minute|
    strip.set_all(r: 0, g: 0, b: 0)
    client.write(strip)

    clock.time = Time.parse("#{hour}:#{minute}")
    color_picker = WordClock::ColorPicker.new(WordClock::XkcdColors.new)
    warn clock.time

    clock.pixels.each do |i|
      color = color_picker.choose(clock.time)
      strip.pixels[i].set({ r: color.red, g: color.green, b: color.blue })
    end

    client.write(strip)

    sleep 0.2
  end
end
