#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'word_clock/clock_24'
require 'word_clock/minumum_luminance_sampler'
require 'faderuby'

if ARGV.size.zero?
  clock = WordClock::Clock24.new
elsif 1 == ARGV.size
  time = Time.parse(ARGV.first)
  clock = WordClock::Clock24.new(time)
else
  warn "Unknown arguments #{ARGV}"
  exit 1
end

client = FadeRuby::Client.new(
  ENV.fetch('OPC_HOST', 'localhost'),
  ENV.fetch('OPC_PORT', '7890').to_i
)

strip = FadeRuby::Strip.new(18 * 16)
strip.set_all(r: 0, g: 0, b: 0)
client.write(strip)

color = WordClock::MinumumLuminanceSampler.new(100..150).sample.to_h

clock.pixels.each do |i|
  strip.pixels[i].set(color)
end

client.write(strip)
