#!/usr/bin/env ruby -I lib
# frozen_string_literal: true

#
# Convert an image to PNM format with
#
# convert -resize '18x16' image.png image.pnm
#

require 'pnm'
require 'faderuby'

if ARGV.empty?
  warn 'Error: Need at least one PNM file to show'
  exit 1
end

client = FadeRuby::Client.new(
  ENV.fetch('OPC_HOST', 'localhost'),
  ENV.fetch('OPC_PORT', '7890').to_i
)

matrix = FadeRuby::Matrix.new(18, 16)
matrix.set_all(r: 0, g: 0, b: 0)
client.write(matrix)

PNM.read(ARGV.first).pixels.each.with_index do |row, y|
  row.each.with_index do |pixel, x|
    matrix[x, y] = FadeRuby::Pixel.new(*pixel)
  end
end

client.write(matrix)
