#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'word_clock/clock_24'
require 'word_clock/terminal/client'
require 'word_clock/terminal/strip'

if ARGV.size.zero?
  clock = WordClock::Clock24.new
elsif 1 == ARGV.size
  time = Time.parse(ARGV.first)
  clock = WordClock::Clock24.new(time)
else
  warn "Unknown arguments #{ARGV}"
  exit 1
end

client = WordClock::Terminal::Client.new(
  STDOUT,
  18, 16
  )

strip = WordClock::Terminal::Strip.new(clock)

color = { r: rand(50..255), g: rand(50..255), b: rand(50..255) }

clock.pixels.each do |i|
  strip.pixels[i].set(color)
end

client.write(strip)
