#!/usr/bin/env ruby
# frozen_string_literal: true

#
# Convert an image to PNM format with
#
# convert -resize '18x16' image.png image.pnm
#

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'pnm'
require 'faderuby'

if ARGV.empty?
  warn 'Error: Need at least one PNM file to show'
  exit 1
end

client = FadeRuby::Client.new(
  ENV.fetch('OPC_HOST', 'localhost'),
  ENV.fetch('OPC_PORT', '7890').to_i
)

WIDTH = 18
HEIGHT = 16

strip = FadeRuby::Strip.new(WIDTH * HEIGHT)
strip.set_all(r: 0, g: 0, b: 0)
client.write(strip)

PNM.read(ARGV.first).pixels.each.with_index do |row, y|
  row.each.with_index do |pixel, x|
    idx = (y * WIDTH) + x
    strip.pixels[idx].set(r: pixel[0], g: pixel[1], b: pixel[2])
  end
end

client.write(strip)
