#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'word_clock/clock_24'
require 'word_clock/xkcd_color_sampler'
require 'word_clock/color_picker'
require 'word_clock/terminal/client'
require 'word_clock/terminal/strip'

if ARGV.size.zero?
  time = Time.now
elsif ARGV.size == 1
  time = Time.parse(ARGV.first)
else
  warn "Unknown arguments #{ARGV}"
  exit 1
end

clock = WordClock::Clock24.new(time)
strip = WordClock::Terminal::Strip.new(clock)
color_picker = WordClock::ColorPicker.new(WordClock::XkcdColorSampler.new)

clock.pixels.each do |i|
  color = color_picker.choose(time)
  strip.pixels[i].set(color)
end

WordClock::Terminal::Client.new(STDOUT, 18, 16).write(strip)
