#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'word_clock/clock_24'
require 'word_clock/minumum_luminance_sampler'
require 'word_clock/xkcd_colors'
require 'word_clock/calendar_facade'
require 'faderuby'

if ARGV.size.zero?
  time = Time.now
elsif 1 == ARGV.size
  time = Time.parse(ARGV.first)
else
  warn "Unknown arguments #{ARGV}"
  exit 1
end

clock = WordClock::Clock24.new(time)

client = FadeRuby::Client.new(
  ENV.fetch('OPC_HOST', 'localhost'),
  ENV.fetch('OPC_PORT', '7890').to_i
)

strip = FadeRuby::Strip.new(18 * 16)
strip.set_all(r: 0, g: 0, b: 0)
client.write(strip)

color_picker = WordClock::ColorPicker.new(WordClock::XkcdColors.new)

clock.pixels.each do |i|
  color = color_picker.choose(time)
  strip.pixels[i].set(color.to_h)
end

client.write(strip)
