#!/usr/bin/env ruby

require 'json'

points = []

scale = 10.to_f

max_x = 17
shift_x = 0 # -max_x / scale

max_z = 15
shift_z = 0 # -max_z / scale

(0..max_x).each do |x|
  y = 0
  (0..max_z).each do |z|
    points << {
      'point' => [
        x.to_f / scale + shift_x,
        y,
        z.to_f / scale + shift_z
      ]
    }
  end
end

puts points.to_json
